app:
    host: "http://localhost"
backend:
    port: 6001
    login_url_suffix: "api/auth/login"
    redirect_uri_suffix: "api/auth/callback"
database:
    port: 6002
frontend:
    port: 3001
secrets:
    login_state_secret: "7ffdbecc-ab7d-4134-9307-2dfcc52f7475"
    session_cookie_secret: "a8f5f167f44f4964e6c998dee827110c"
wristband:
    secure: "false"
    custom_application_login_page_url: ""
    dangerously_disable_secure_cookies: "true"
    root_domain: ""
    scopes: "openid, offline_access, email"
    use_custom_domains: "false"
    use_tenant_subdomains: "false"
logging:
    level: "INFO"
gcp:
    label: "Wristband FastAPI App Demo"
    id: "wb-fastapi-demo-app"
    description: "A fastapi demo app for wristband"