[project]
name = "src"
version = "0.1.0"
description = ""
authors = [
    {name = "fddiferd",email = "fddiferd@gmail.com"}
]
requires-python = ">=3.11"
dependencies = [
    "pytest (>=8.3.4,<9.0.0)",
    "python-dotenv (>=1.0.1,<2.0.0)",
    "cryptography (>=44.0.0,<45.0.0)",
    "requests (>=2.32.3,<3.0.0)",
    "fastapi (>=0.115.12,<0.116.0)",
    "uvicorn (>=0.34.0,<0.35.0)",
    "firebase-admin (>=6.8.0,<7.0.0)",
    "dotenv (>=0.9.9,<0.10.0)",
    "wristband (==4.3.1)",
    "pyyaml (>=6.0.2,<7.0.0)",
]