import secrets

# Simple lists for generating nicknames
ADJECTIVES = [
    "Big",
    "Little",
    "Fat",
    "Thin",
    "Crazy",
    "Mad",
    "Wild",
    "Smooth",
    "Sharp",
    "Lucky",
    "Fast",
    "Slow",
    "Cold",
    "Hot",
    "Wise",
    "Young",
    "Deadly",
    "Silent",
    "Fierce",
    "Slick",
    "Tough",
    "Clever",
    "Bold",
    "Sneaky",
    "Quick",
    "Heavy",
    "Silver",
    "Golden",
    "Dark",
    "Bright",
    "Iron",
    "Steel",
]
NICKNAMES = [
    "Tony",
    "Sal",
    "Vinny",
    "Joey",
    "Frankie",
    "Rocco",
    "Gino",
    "Marco",
    "Carlo",
    "Nico",
    "Luca",
    "Dante",
    "Angelo",
    "Bruno",
    "Rico",
    "Vito",
    "Jimmy",
    "Sophia",
    "Isabella",
    "Maria",
    "Lucia",
    "Carmela",
    "Rosa",
    "Bianca",
    "Valentina",
    "Francesca",
    "Stella",
    "Gabriella",
    "Adriana",
    "Elena",
    "Caterina",
    "Alessandra",
    "Salvatore",
    "Giovanni",
    "Antonio",
    "Giuseppe",
    "Matteo",
    "Lorenzo",
    "Leonardo",
    "Francesco",
    "Alessandro",
    "Stefano",
    "Roberto",
    "Michele",
    "Fabio",
    "Domenico",
    "Emilio",
    "Sergio",
    "Giulia",
    "Chiara",
    "Federica",
    "Martina",
    "Silvia",
    "Paola",
    "Laura",
    "Anna",
    "Cristina",
    "Monica",
    "Simona",
    "Valeria",
    "Claudia",
    "Barbara",
    "Teresa",
    "Giovanna",
]
TITLES = [
    "The Bull",
    "The Fish",
    "The Hammer",
    "The Knife",
    "The Shadow",
    "The Snake",
    "The Wolf",
    "The Fox",
    "The Eagle",
    "The Lion",
    "The Tiger",
    "The Bear",
    "The Shark",
    "The Cat",
    "The Dog",
    "The Rat",
    "The Boss",
    "The Ghost",
    "The Blade",
    "The Ice",
    "The Fire",
    "The Rock",
    "The Machine",
    "The Storm",
    "The Thunder",
    "The Lightning",
    "The Tornado",
    "The Hurricane",
    "The Bullet",
    "The Cannon",
    "The Bomb",
    "The Enforcer",
]


def generate_nickname() -> str:
    return secrets.choice(
        [
            f"{secrets.choice(ADJECTIVES)} {secrets.choice(NICKNAMES)}",
            f"{secrets.choice(NICKNAMES)} {secrets.choice(TITLES)}",
            f"{secrets.choice(ADJECTIVES)} {secrets.choice(NICKNAMES)} {secrets.choice(TITLES)}",
        ]
    )
